# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=255, unique=True)),
                ('keywords', models.CharField(max_length=2048, unique=True)),
                ('url', models.CharField(max_length=2048, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=10, unique=True)),
                ('pubdate', models.CharField(max_length=255, null=True)),
                ('source', models.CharField(max_length=255, null=True)),
                ('authors', models.CharField(max_length=2048, null=True)),
                ('title', models.CharField(max_length=2048, null=True)),
                ('sortpubdate', models.CharField(max_length=255, null=True)),
                ('year', models.IntegerField(default=0, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pubmed.Category')),
            ],
        ),
    ]
